# A generic, single database configuration.

[alembic]
script_location = %(here)s/alembic
prepend_sys_path =.
path_separator = os

# URL DO NEON - sem channel_binding que dá erro no Windows
sqlalchemy.url = postgresql://neondb_owner:npg_wYCKyqhgtO03@ep-lively-glitter-b5hyfr8o-pooler.c-7.us-east-2.aws.neon.tech/connect-db?sslmode=require

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
