"""add banners comments views shares

Revision ID: 4a91a7bf08fe
Revises: 57a6750a5afa
Create Date: 2026-09-28 20:40:21.632581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a91a7bf08fe'
down_revision: Union[str, Sequence[str], None] = '57a6750a5afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('titulo', sa.String(length=255), nullable=False),
        sa.Column('imagem_url', sa.String(length=500), nullable=False),
        sa.Column('link_url', sa.String(length=500), nullable=True),
        sa.Column('posicao', sa.Enum('home_topo', 'home_meio', 'sidebar', 'dentro_post', 'footer', name='bannerposicao'), nullable=False),
        sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('views', sa.Integer(), server_default='0', nullable=False),
        sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
        sa.Column('data_inicio', sa.DateTime(), nullable=True),
        sa.Column('data_fim', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('post_id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.Column('conteudo', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    # CORREÇÃO: com default 0 pros posts antigos não quebrar
    op.add_column('posts', sa.Column('views', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('shares_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'shares_count')
    op.drop_column('posts', 'views')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('banners')
    # ### end Alembic commands ###
